eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 8765

spring:
  application:
    name: post-service

  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: ${DB_URI:mongodb://localhost:27017/high-five}
      database: high-five
      uuid-representation: standard

cloudinary:
  url: ${CLOUDINARY_URL}